# Generated by Django 6.1.1 on 2026-10-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=22, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('genero', models.CharField(max_length=50)),
                ('subgenero', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=22, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('artista', models.CharField(max_length=300)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('popularidad', models.PositiveSmallIntegerField()),
                ('duracion_ms', models.PositiveIntegerField()),
                ('fecha_lanzamiento', models.CharField(blank=True, max_length=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('playlists', models.ManyToManyField(related_name='canciones', to='catalogo.playlist')),
            ],
            options={
                'verbose_name_plural': 'Canciones',
                'ordering': ['-popularidad'],
            },
        ),
    ]
