# Generated by Django 6.1.1 on 2026-10-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_playlist_remove_cancion_genero_cancion_playlists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='fecha_creacion',
            new_name='creada_en',
        ),
    ]
